import { createFileRoute } from "@tanstack/react-router";
import { ArrowDownToLine, FileArchive, FileText } from "lucide-react";
import { PageIntro, SiteShell } from "@/components/site-shell";
import { publicUrl, siteUrl } from "@/lib/site-url";
const thesisArtwork = publicUrl("/assets/outreach/6.jpg");

export const Route=createFileRoute("/notes")({head:()=>({meta:[{title:"Didactical Notes — Daniel Panizo"},{name:"description",content:"Notes, solved physics problems and LaTeX templates by Daniel Panizo."},{property:"og:title",content:"Didactical Notes — Daniel Panizo"},{property:"og:description",content:"Learning materials for cosmology, gravitation and electrodynamics."},{property:"og:type",content:"website"},{property:"og:url",content:siteUrl("notes")},{name:"twitter:card",content:"summary"}],links:[{rel:"canonical",href:siteUrl("notes")}]}),component:Notes});
const root=publicUrl("downloads/");
const groups: Array<{ title: string; caption: string; items: Array<[string, string]> }> = [
 {title:"Research notes",caption:"Based on doctoral research",items:[["Cosmology: Classical & Quantum","notes/cosmology.pdf"],["Instantons","notes/instantons.pdf"],["Hypersurfaces","notes/hypersurfaces.pdf"],["Dark Bubble lecture notes","notes/lecture_notes_DB.pdf"]]},
 {title:"Solved problems",caption:"Worked university-level exercises",items:[["Electrodynamics","notes/solved_problems_electrodynamics.pdf"],["Gravitation","notes/solved_problems_GR.pdf"]]},
 {title:"LaTeX templates",caption:"Reusable document systems",items:[["Simple document","templates/simple_doc_template.zip"],["Set of notes","templates/notes_template.zip"],["Modern CV","templates/mod_moderncv_template.zip"]]},
];
function Notes(){return <SiteShell><div className="mx-auto max-w-6xl px-4 py-5 md:px-8 md:py-8"><div className="grid grid-cols-12 gap-4">
  <PageIntro eyebrow="Didactical notes" title="Knowledge, made shareable."><p>Research notes, solved exercises and practical LaTeX templates.</p></PageIntro>
  <a className="panel-link zoom-tile group relative col-span-12 flex min-h-48 flex-col justify-between overflow-hidden bg-card p-6 sm:col-span-4" href="http://www.diva-portal.org/smash/record.jsf?pid=diva2%3A1847954" target="_blank" rel="noreferrer"><img src={thesisArtwork} alt="Dark bubble landscape illustration" className="zoom-tile-image absolute inset-0 size-full object-cover object-[50%_80%] opacity-70 group-hover:scale-[1.03] group-hover:opacity-90"/><span className="absolute inset-0 bg-gradient-to-b from-background/40 via-background/25 to-background/95"/><div className="relative flex items-center justify-between"><span className="eyebrow text-foreground">Thesis</span><ArrowDownToLine className="size-4 text-primary transition-transform group-hover:translate-y-1"/></div><div className="relative"><p className="font-display text-xl font-semibold opacity-70 transition-opacity duration-300 group-hover:opacity-90">Blowing Bubbles from String Theory</p><p className="mt-2 text-xs text-muted-foreground">PhD thesis · 2024</p></div></a>
  {groups.map(group=><article key={group.title} className="panel col-span-12 p-6 sm:col-span-4"><h2 className="font-display text-xl font-semibold">{group.title}</h2><p className="mt-2 text-xs text-muted-foreground">{group.caption}</p><div className="mt-6">{group.items.map(([name,path])=><a key={name} href={root+path} target="_blank" rel="noreferrer" className="group flex min-h-14 items-center justify-between gap-3 border-t border-border py-3"><span className="flex items-center gap-3">{path.endsWith(".zip")?<FileArchive className="size-3.5 text-primary"/>:<FileText className="size-3.5 text-primary"/>}<span className="text-xs font-semibold">{name}</span></span><ArrowDownToLine className="size-3.5 shrink-0 text-muted-foreground transition-transform group-hover:translate-y-1"/></a>)}</div></article>)}
</div></div></SiteShell>}
