/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MagicRouteImport } from './routes/magic'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as OutlineRouteImport } from './routes/outline'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as SlidesRouteImport } from './routes/slides'
import { Route as OutreachIndexRouteImport } from './routes/outreach.index'
import { Route as OutreachHistoryRouteImport } from './routes/outreach.history'
import { Route as OutreachPostcardsRouteImport } from './routes/outreach.postcards'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicRoute = MagicRouteImport.update({
  id: '/magic',
  path: '/magic',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const OutlineRoute = OutlineRouteImport.update({
  id: '/outline',
  path: '/outline',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesRoute = SlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachIndexRoute = OutreachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachHistoryRoute = OutreachHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachPostcardsRoute = OutreachPostcardsRouteImport.update({
  id: '/postcards',
  path: '/postcards',
  getParentRoute: () => OutreachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/magic': typeof MagicRoute
  '/notes': typeof NotesRoute
  '/outline': typeof OutlineRoute
  '/outreach': typeof OutreachRouteWithChildren
  '/slides': typeof SlidesRoute
  '/outreach/history': typeof OutreachHistoryRoute
  '/outreach/postcards': typeof OutreachPostcardsRoute
  '/outreach/': typeof OutreachIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/magic': typeof MagicRoute
  '/notes': typeof NotesRoute
  '/outline': typeof OutlineRoute
  '/slides': typeof SlidesRoute
  '/outreach/history': typeof OutreachHistoryRoute
  '/outreach/postcards': typeof OutreachPostcardsRoute
  '/outreach': typeof OutreachIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/magic': typeof MagicRoute
  '/notes': typeof NotesRoute
  '/outline': typeof OutlineRoute
  '/outreach': typeof OutreachRouteWithChildren
  '/slides': typeof SlidesRoute
  '/outreach/history': typeof OutreachHistoryRoute
  '/outreach/postcards': typeof OutreachPostcardsRoute
  '/outreach/': typeof OutreachIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/magic'
    | '/notes'
    | '/outline'
    | '/outreach'
    | '/slides'
    | '/outreach/history'
    | '/outreach/postcards'
    | '/outreach/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/magic'
    | '/notes'
    | '/outline'
    | '/slides'
    | '/outreach/history'
    | '/outreach/postcards'
    | '/outreach'
  id:
    | '__root__'
    | '/'
    | '/magic'
    | '/notes'
    | '/outline'
    | '/outreach'
    | '/slides'
    | '/outreach/history'
    | '/outreach/postcards'
    | '/outreach/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MagicRoute: typeof MagicRoute
  NotesRoute: typeof NotesRoute
  OutlineRoute: typeof OutlineRoute
  OutreachRoute: typeof OutreachRouteWithChildren
  SlidesRoute: typeof SlidesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic': {
      id: '/magic'
      path: '/magic'
      fullPath: '/magic'
      preLoaderRoute: typeof MagicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outline': {
      id: '/outline'
      path: '/outline'
      fullPath: '/outline'
      preLoaderRoute: typeof OutlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides': {
      id: '/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof SlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach/': {
      id: '/outreach/'
      path: '/'
      fullPath: '/outreach/'
      preLoaderRoute: typeof OutreachIndexRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/history': {
      id: '/outreach/history'
      path: '/history'
      fullPath: '/outreach/history'
      preLoaderRoute: typeof OutreachHistoryRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/postcards': {
      id: '/outreach/postcards'
      path: '/postcards'
      fullPath: '/outreach/postcards'
      preLoaderRoute: typeof OutreachPostcardsRouteImport
      parentRoute: typeof OutreachRoute
    }
  }
}

interface OutreachRouteChildren {
  OutreachHistoryRoute: typeof OutreachHistoryRoute
  OutreachPostcardsRoute: typeof OutreachPostcardsRoute
  OutreachIndexRoute: typeof OutreachIndexRoute
}

const OutreachRouteChildren: OutreachRouteChildren = {
  OutreachHistoryRoute: OutreachHistoryRoute,
  OutreachPostcardsRoute: OutreachPostcardsRoute,
  OutreachIndexRoute: OutreachIndexRoute,
}

const OutreachRouteWithChildren = OutreachRoute._addFileChildren(
  OutreachRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MagicRoute: MagicRoute,
  NotesRoute: NotesRoute,
  OutlineRoute: OutlineRoute,
  OutreachRoute: OutreachRouteWithChildren,
  SlidesRoute: SlidesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
